### ISSUE TITLE
json_parser.py

### ISSUE THREAD

**Issue by evabronskayaa** [FazylovV/videohosting_dwh#5]
```python
def parse_video(data: dict):
    video_id = data['id']
    snippet = data['snippet']
    title = snippet['title']
    description = snippet['description']
    published_at = snippet['publishedAt']
    return video_id, title, description, published_at
```

Если используешь type hint dict, то необходимо указывать тип ключа и значений. Например, dict[str, str]
+тут output type не хватает

**Comment by FazylovV** [comment]
Так output type добавил, но как мне указать тип ключа и тип значения, если ключ строка, а значением может быть как строка, так и еще один dict, потому что там json

**Comment by evabronskayaa** [comment]
@FazylovV 
dict[str, str | dict [str, str]]

https://docs.python.org/3/library/typing.html#typing.Union

**Comment by FazylovV** [comment]
А если вложенность большая?
Например вот так: dict[str, str | dict[str, str | dict[str, str | dict[str, str | dict[str, str]]]]

**Comment by evabronskayaa** [comment]
@FazylovV то хотя бы отразить концептульно dict[str, str | dict]

**Comment by FazylovV** [comment]
Сделал
