### ISSUE TITLE
yotube_service.py

### ISSUE THREAD

**Issue by evabronskayaa** [FazylovV/videohosting_dwh#6]
youtube_service.py

**Comment by evabronskayaa** [comment]
Импорты не по PEP

```python
import asyncio
from googleapiclient.discovery import build
from pytube import YouTube
import requests
import aiohttp
import re
import json
import generator
from database_service import *
from json_parser import *
```

Сначала системные, потом инсталлируемые, затем проектные

**Comment by evabronskayaa** [comment]
try-except используется для отлавливания ошибок, добавь хотя бы тип ошибок, которую пропускаем и логирование
```python 
               try:
                    custom_url = channel_data['items'][0]['snippet']['customUrl']
                except:
                    continue
```

**Comment by evabronskayaa** [comment]
Кажется у кода нет форматирования
Добавь форматтер (например, BlackFormatter) или пре-коммиты

**Comment by FazylovV** [comment]
BlackFormatter добавил, импорты подправил, исключение и логирование еще не сделал

**Comment by evabronskayaa** [comment]
@FazylovV 
поменяй еще нейминг модуля
у тебя yotube_service.py -> yo**u**tube_service.py

**Comment by FazylovV** [comment]
Сделал
